# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_list"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = " maintain sorted lists of INTRINSIC type"
categories = ["list"]
keywords = ["fortran", "list", "dictionary" ]
homepage = "https://github.com/urbanjost/M_list.git"

[install]
   library=true

[dev-dependencies]
   M_sort    = { git = "https://github.com/urbanjost/M_sort.git" }

[[test]]
   name="test_suite"
   source-dir="test"
   main="test_suite_M_list.f90"

[test.dependencies]
   M_framework          = { git = "https://github.com/urbanjost/M_framework.git" }
